#!/usr/bin/env bash

set -e

if [ "master" != "$TRAVIS_BRANCH" ]
then
  exit 0
fi

kubectl create -f graphite-replication-controller.yml
kubectl create -f graphite-service.yml
kubectl create -f grafana-pod.yml
kubectl create -f grafana-service.yml
