apiVersion: v1
kind: ReplicationController
metadata:
  name: graphite
  labels:
    name: graphite
    context: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: graphite
        context: default
    spec:
      containers:
      - name: graphite
        image: nickstenning/graphite
        ports:
        - containerPort: 80
        - containerPort: 2003
        - containerPort: 2004
        - containerPort: 7002
